### ISSUE TITLE
The repository doesn't have LICENSE

### ISSUE THREAD

**Issue by HarukaMa** [googollee/eviltransform#18]
Without a license, it's unclear whether we can use the code in different projects.

**Comment by Arthur2e5** [comment]
+1

**Comment by Arthur2e5** [comment]
Personally I suggest using 2-clause BSD for this repo, if someone is really going to use it in production.

This repo is (currently) just an example of *how to express the formulas in a C/Python/Haskell/...-ish way*. Since formulas aren't really protected by copyright (patents are not in our scope of discussion), why not just use some very loose licenses and hope someone will directly use our lib and give some attribution?

* * *

So there are already 12 [contributors](https://github.com/googollee/eviltransform/graphs/contributors) in this repo, and we can mention them all to discuss this.

@googollee @gutenye @xingxing @bewantbe @GhostFlying @larryli @gumblex @lbt05 @chenweiyj

Contributors below has only sent trivial non-algorithmic corrections, and we might be able to go without their permission:

@Orthocenter @LennonShawn @josh-taylr

**Comment by gutenye** [comment]
@Arthur2e5 I'm familiar with MIT, GPL but not BSD, can you explain more about BSD?

**Comment by Arthur2e5** [comment]
2-Clause BSD License is a super stripped-down version of the original BSD. It can be almost considered as an equivalent to MIT. The requirements for this License are:

> (a broken version, see original at http://opensource.org/licenses/bsd-license.php)
> `Copyright (C) 2333-6666 Foo Bar <foo@bar.com>`
> `Copyright (C) 0001-9999 Random J Spoofer`
>
> 1. Leave some attributioon: Everything including this piece of code need to include this trunk of notice and the Copyright lines above. For binaries, you have to be able to reproduce (e.g., show in a dialog or so) the whole thing, plus *other materials* (what's that?).
> (ah yes I merged [1] and [2])
> 2. as is, ABSOLUTELY NO WARRANTY.
>

**Comment by gumblex** [comment]
Translation is a kind of modification, so the license should depend on the original copyright holder.

**Comment by Arthur2e5** [comment]
@gumblex 

http://copyright.gov/circs/circ61.pdf

> Copyright protection is not available for ideas, program logic, **algorithms**, systems, methods, concepts, or layouts.

Remember that Copyright only protects the *form of expression*, not the *idea*.

**Comment by gumblex** [comment]
@Arthur2e5 I just **translated** the Python version from the JavaScript version, not wrote down the algorithms on my own, so it _is_ the _form of expression_.

**Comment by Arthur2e5** [comment]
So find a girlfriend and let she tell you what she saw. And transform the whole repo in this way.

**Comment by gutenye** [comment]
Thanks for the classification, and the devil is in the details, I just go
with BSD.

On Mon, Feb 1, 2016 at 12:23 PM, Mingye Wang <notifications@github.com>
wrote:

> So find a girlfriend and let she tell you what she saw. And transform the
> whole repo in this way.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/googollee/eviltransform/issues/18#issuecomment-177755625>
> .
>



-- 
Linux, Vim, Ruby, Go and Javascript
- Guten.me  <http://GutenYe.com>
- GitHub.com/GutenYe <http://Github.com/GutenYe>

**Comment by Arthur2e5** [comment]
@gutenye So, two-clause BSD? Problem 35% solved. Great.

**Comment by gutenye** [comment]
@Arthur2e5 YES

**Comment by googollee** [comment]
I'm OK with 2-Clause BSD. What other contributor's opinion? cc @gutenye @xingxing @bewantbe @GhostFlying @larryli @gumblex @lbt05 @chenweiyj

**Comment by gumblex** [comment]
No problem.

**Comment by lbt05** [comment]
Looks good from me

**Comment by bewantbe** [comment]
No problem for me.
