### ISSUE TITLE
Noob question: does this fix the GPS deviation issue?

### ISSUE THREAD

**Issue by dandv** [googollee/eviltransform#6]
I'm just [beginning to understand the GPS offset problem in China](http://gis.stackexchange.com/questions/141542/what-causes-gps-offset-in-china), and it seems that it is caused by both the different projection system used, and by the [GPS deviation](https://github.com/maxime/ChinaMapDeviation/issues/1) that must be legally be introduced by either GPS manufacturers, or map providers (unclear on this).

So does the code in this repo fix both issues?

The goal would be to copy the coordinates of a place from the maps.google.com URL, transform them, paste the result in Baidu Maps, and get the same location displayed.

Does [this jsbin](http://jsbin.com/panomu/1/) also solve the problem by calling Baidu Maps' conversion API?

**Comment by fengzee-me** [comment]
Yes, it does.

Based on what I actually experience using and developing LBS apps, it is mainly the difference of coordination system (GCJ-02 vs. WGS-84) that causes all the messy problems. I'm not 100% sure if GPS manufacturers would make their device to report false coordinates, but it's unlikely since I have never find a single scene where there is still a problem after I converted WGS-84 (the de facto standard of rest of the world) coordinates to GCJ-02 (the Chinese map providers are forced to use this coordination system with their products) using the algorithm in this repo. There's a extra coordination system, BD-09, involved, specially for Baidu Maps.

For your application, just try transforming your coordinates from maps.google.com (WGS-84) system to BD-09. And I think it will display the same location on Baidu Maps. (Although for myself I've been using GCJ-02 maps (eg. Autonavi Maps) only. So I'm not sure.)

**Comment by fengzee-me** [comment]
An extra notice: please also consider the possibility that coordinates maps.google.com provides are also in GCJ-02 (so try a GCJ-02 to BD-09 transform if you need). As I know, Google's map data in China is provided by Autonavi, which is using GCJ-02.

**Comment by dandv** [comment]
For the same coordinates in [my jsbin example](http://jsbin.com/panomu/1/), the Bund Museum at 31.2423 / 121.4914, OpenStreetMap is off by about 700 meters in the other direction: https://www.openstreetmap.org/?mlat=31.2423&mlon=121.4914&zoom=17.

I'm confused at this point.

If I go to China and take a picture with my GPS-enabled US smartphone, then come back and plot that picture on Google's Map, will it show up in the wrong spot?

What if someone with a Chinese smartphone takes a picture and sends it to me, will it show up in the right spot because GPS devices in China correct for the deviation?

What if I plot both pictures on OSM? Or Baidu? What conversion do I need to make?

**Comment by fengzee-me** [comment]
Sorry I'm not very knowledgeable at specific causes. Of course an ultimate answer is: please try.

But please notice it might be more efficient to say "an App using map API provided by a Chinese map provider" than "a Chinese smartphone" when you design your experiments.

**Comment by fengzee-me** [comment]
Sorry I'm not very knowledgeable at specific cases. Of course an ultimate answer is: please try.

But please notice it might be more efficient to say "an App using map API provided by a Chinese map provider" than "a Chinese smartphone" when you design your experiments.

**Comment by dandv** [comment]
I've posted code to try the difference at http://jsbin.com/panomu/2/watch?js,output

It gets the current position via the navigator.geolocation API and adds a marker to the Baidu Map at that location. Then it converts the marker to Baidu's coordinates using their API, and adds the converted marker too.

If you're located in China, could you give it a try and please let me know which of the two markers is correct?

**Comment by googollee** [comment]
Seems Baidu's coordinates (which named as BD-09) is different from GCJ-02. And BD-09 can map to GCJ-02.

You can try this patch https://github.com/googollee/eviltransform/pull/11 to see if it works. After I finished other language and format issue, it will merge to main branch.

**Comment by googollee** [comment]
Close issue. Reopen if anyone has more problem.

**Comment by dandv** [comment]
I've created a [Wikipedia article section](https://en.wikipedia.org/wiki/Baidu_Maps#Coordinate_system) about the differences in the coordinate systems.
